"""Изменение роли на администратора

Revision ID: de7f56853b8c
Revises: bfbef48a85fa
Create Date: 2024-10-04 01:19:49.549581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de7f56853b8c'
down_revision = 'bfbef48a85fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('main_office', sa.String(length=255), nullable=True),
    sa.Column('additional_offices', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('managers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=15), nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('main_office', sa.VARCHAR(length=255), nullable=True),
    sa.Column('additional_offices', sa.VARCHAR(length=255), nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('administrators')
    # ### end Alembic commands ###
